packages: use growpart instead of gptfdisk
sgdisk is shit really, it never resizes correctly

diff --git a/packages/tobuild/mkinitcpio-archiso/0001-Adapt-to-how-demolinux-works.patch b/packages/tobuild/mkinitcpio-archiso/0001-Adapt-to-how-demolinux-works.patch
--- a/packages/tobuild/mkinitcpio-archiso/0001-Adapt-to-how-demolinux-works.patch
+++ b/packages/tobuild/mkinitcpio-archiso/0001-Adapt-to-how-demolinux-works.patch
@@ -1,15 +1,15 @@
-From aed5cb1e475c2508a6d2ff2f7d33c45f7e9756d4 Mon Sep 17 00:00:00 2001
+From 49fbffdbc57dcf3990ef21e37f05da74b0ded366 Mon Sep 17 00:00:00 2001
 From: demostanis <demostanis@protonmail.com>
-Date: Tue, 31 Dec 2024 18:04:12 +0100
+Date: Fri, 3 Jan 2025 03:22:46 +0100
 Subject: [PATCH] Adapt to how demolinux works
 
 ---
- hooks/archiso   | 110 ++++++++++++++++++++++++++++++------------------
+ hooks/archiso   | 112 ++++++++++++++++++++++++++++++------------------
  install/archiso |   5 +++
- 2 files changed, 74 insertions(+), 41 deletions(-)
+ 2 files changed, 75 insertions(+), 42 deletions(-)
 
 diff --git a/hooks/archiso b/hooks/archiso
-index d2c600e..dba239c 100644
+index d2c600e..34a8788 100644
 --- a/hooks/archiso
 +++ b/hooks/archiso
 @@ -45,13 +45,13 @@ _mnt_dmsnapshot() {
@@ -59,24 +59,12 @@ index d2c600e..dba239c 100644
      # shellcheck disable=SC2154
      # defined via initcpio's parse_cmdline()
      if [ -n "${cow_label}" ]; then
-@@ -211,21 +200,53 @@ archiso_mount_handler() {
+@@ -210,22 +199,54 @@ archiso_mount_handler() {
+     local newroot="${1}"
      local sigfile cms_sigfile fs_img fs_img_size iso_blockdev
  
-     if ! mountpoint -q "/run/archiso/bootmnt"; then
+-    if ! mountpoint -q "/run/archiso/bootmnt"; then
 -        _mnt_dev "${archisodevice}" "/run/archiso/bootmnt" "-r" "defaults"
-+        _mnt_dev /dev/disk/by-partlabel/boot "/run/archiso/bootmnt" "-r" "defaults"
-     fi
- 
--    # We need this block at the top for early failure
--    # but also to be able to give the fs_img to CMS verification.
--    # (sha512sum files contain the image, CMS files does not)
--    if [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.sfs" ]; then
--        fs_img="/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.sfs"
--    elif [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.erofs" ]; then
--        fs_img="/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.erofs"
--    else
--        echo "ERROR: no root file system image found"
--        launch_interactive_shell
 +    btrfs_root=/run/archiso/btrfs
 +    _mnt_dev /dev/disk/by-partlabel/system $btrfs_root "-w" "subvol=system,compress=zstd"
 +
@@ -86,11 +74,11 @@ index d2c600e..dba239c 100644
 +
 +        # first, resize the filesystem
 +        umount -f $btrfs_root
-+        # TODO: multiple system partitions
-+        disk="$(lsblk -no pkname /dev/disk/by-partlabel/system)"
 +        # then, resize the partition to fit the whole disk...
-+        sgdisk -d 3 -N 3 -c 3:system /dev/"$disk"
-+        partprobe
++        # TODO: multiple system partitions
++        disk=/dev/"$(lsblk -no pkname /dev/disk/by-partlabel/system)"
++        growpart "$disk" 3
++        partprobe "$disk"
 +
 +        plymouth update --status="Creating Btrfs subvolumes..."
 +
@@ -103,6 +91,20 @@ index d2c600e..dba239c 100644
 +        btrfs subvol create $btrfs_root/data
 +        btrfs subvol create $btrfs_root/swap
 +        btrfs filesystem mkswapfile --size 4G --uuid clear $btrfs_root/swap/swapfile 2>/dev/null
+     fi
+ 
+-    # We need this block at the top for early failure
+-    # but also to be able to give the fs_img to CMS verification.
+-    # (sha512sum files contain the image, CMS files does not)
+-    if [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.sfs" ]; then
+-        fs_img="/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.sfs"
+-    elif [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.erofs" ]; then
+-        fs_img="/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.erofs"
+-    else
+-        echo "ERROR: no root file system image found"
+-        launch_interactive_shell
++    if ! mountpoint -q "/run/archiso/bootmnt"; then
++        _mnt_dev /dev/disk/by-partlabel/boot "/run/archiso/bootmnt" "-r" "defaults"
      fi
  
 +    plymouth update --status="Mouting filesystems..."
@@ -174,7 +176,6 @@ index d2c600e..dba239c 100644
      fi
  }
  
-diff --git a/install/archiso b/install/archiso
 --- a/install/archiso
 +++ b/install/archiso
 @@ -7,6 +7,7 @@ build() {
@@ -185,14 +186,17 @@ diff --git a/install/archiso b/install/archiso
  
      add_runscript
  
-@@ -14,6 +15,10 @@ build() {
+@@ -14,6 +15,13 @@ build() {
      add_binary dmsetup
      add_binary losetup
      add_binary openssl
 +    add_binary btrfs
-+    add_binary sgdisk
 +    add_binary plymouth
 +    add_binary lsblk
++    add_binary growpart
++    # growpart deps
++    add_binary sgdisk
++    add_binary flock
  
      if command -v pv >/dev/null 2>&1; then
          add_binary pv
